Module3 task1
htmlacademy-react/1378865-six-cities-6 pull request #5
Opened 2021-02-13 21:05 UTC by nikitenkovit

2021-02-14 18:41 UTC, vatokato requested changes
В целом хорошо.
Обязательно нужно решить вопросы с проп тайпсами: [Д25](https://up.htmlacademy.ru/react/6/criteries#d25) При использовании PropTypes сложные типы данных описаны максимально подробно

2021-02-14 18:41 UTC, vatokato commented on src/components/offers-list/offers-list.jsx
> +            handleMouseEnter={handleMouseEnter}
название обработчика норм `handleMouseEnter`, но в компоненты мы должны передавать уже `onMouseEnter`

критерии [Д2](https://up.htmlacademy.ru/react/6/criteries#d2) и [Д11](https://up.htmlacademy.ru/react/6/criteries#d11)

` onMouseEnter={handleMouseEnter}`

2021-02-14 18:41 UTC, vatokato commented on src/components/offers-list/offers-list.jsx
> +  offers: PropTypes.arrayOf(PropTypes.object.isRequired)
здесь нужно проверять не просто на объект, а на конкретный объект. Для этого нужно вынести пропсы объекта в отдельный файл и уже импортировать куда нужно (например сюда и в карточку)

```
Помните, валидация props с помощью пакета PropTypes — это просто объект. Чтобы не нарушать принцип DRY вы можете хранить такие объекты в отдельном файле и импортировать их.
```

2021-02-14 18:41 UTC, vatokato commented on src/components/favorites-screen/favorites-screen.jsx
> +      } // Почему линтер не разрешает делать тернарник тут???
странно, проверю

2021-02-14 18:41 UTC, vatokato commented on src/components/room-screen/room-screen.jsx
> +  const matchedOffer = offers.slice()
Очень странное решение фильтровать именно тут.

Это ведь компонент 1 айтема, сюда должны передаваться конкретные данные.

Давай вынесем это на уровень выше и сделаем как то так:

```
<Route exact path={....}
  render={(routerProps)=>{
  ...
  return (
  <RoomScreen offer = {offer} ... />);
}}/>
```

2021-02-14 18:41 UTC, vatokato commented on src/components/reviews-form/review-form.jsx
> +    setFormValue({...formValue, [name]: value});
отличное решение, но когда в useState сохраняешь не только новые данные, но и данные из этого же стейта лучше пользоваться функцией, чтобы избежать  возможных ошибок из-за асинхронности сохранения:

`setFormValue(state => ({...state, [name]: value}));`

2021-02-15 21:02 UTC, nikitenkovit reviewed
> В целом хорошо.
> Обязательно нужно решить вопросы с проп тайпсами: [Д25](https://up.htmlacademy.ru/react/6/criteries#d25) При использовании PropTypes сложные типы данных описаны максимально подробно

всё сделал кроме переключателя классов в карточке (switchClassNames), это задание следующей домашки в ней буду делать.

2021-02-16 17:32 UTC, vatokato commented on src/components/favorites-screen/favorites-screen.jsx
> -        : generalOffer[offer.city.name] = [offer];
похоже из-за того что push возвращает значение.
```
const tmp = generalOffer.hasOwnProperty(offer.city.name)
        ? generalOffer[offer.city.name].push(offer)
        : generalOffer[offer.city.name] = [offer];
```
вот так все норм, но пусть будет if else, норм выглядит

2021-02-16 17:38 UTC, vatokato approved these changes

2021-02-16 17:38 UTC, merged