Module4 task2
htmlacademy-react/1378865-six-cities-6 pull request #8
Opened 2021-02-18 13:31 UTC by nikitenkovit

2021-02-19 15:46 UTC, vatokato requested changes
В целом хорошо, глаза немного разбегаются от классов, которые летают в пропах из констант. Мне кажется это не совсем правильный подход.

у тебя есть компонент `OfferCardNear`, нет смысла тянуть классы из констант. можно прямо в этом компоненте описать все что нужно:

```
<OfferCard
      offerCardClassName={{
          articleClass: `near-places__card`,
          wrapperClass: `near-places__image-wrapper`,
          infoClass: ``
     }}
      isHoverHandler={true}
      {...props}
    />
```
это нагляднее и удобнее.


еще момент: если ты хранишь проп тайпы в отельном файле рядом с компонентом давай называть их `имя-компонента.prop.js`

2021-02-19 15:46 UTC, vatokato commented on src/components/reviews-list/reviews-list.jsx
> +Review.propTypes = {
на вложенные компоненты вроде не обязательно писать проп тайпсы

не критично

2021-02-19 15:46 UTC, vatokato commented on src/components/bookmark-button/bookmark-button.jsx
>    clickedElement.classList.toggle(className);
очень странное решение по смене класса, как то не по-реактовски )

у тебя ведь есть буль `bookmark` (я бы его назвал `isActive` или `isActiveBookmark`), на его основе можно указывать нужный класс

2021-02-19 15:46 UTC, vatokato commented on src/components/offer-card/offer-card-class-name-prop.js
> +import PropTypes from 'prop-types';
зачем отдельный файл на пропы классов? давай все в `offer-card.prop.js`

2021-02-19 17:53 UTC, nikitenkovit commented on src/components/bookmark-button/bookmark-button.jsx
>    clickedElement.classList.toggle(className);
сделал

2021-02-19 18:18 UTC, nikitenkovit commented on src/components/offer-card/offer-card-class-name-prop.js
> +import PropTypes from 'prop-types';
у меня нет offer-card.prop.js, валидация пропа offer в room-offer-screen.prop.js. просто удалил offer-card-class-name-prop.js и сделал валидацию классов в самой карточке детализированную...

2021-02-19 18:21 UTC, nikitenkovit commented on src/components/reviews-list/reviews-list.jsx
> +Review.propTypes = {
если скажешь - удалю)))

2021-02-19 18:51 UTC, nikitenkovit commented
> еще момент: если ты хранишь проп тайпы в отельном файле рядом с компонентом давай называть их `имя-компонента.prop.js`

кое где переименовал и склеил файлы. но некоторые у меня как и писал в телеге содержат только конкретный проп, поэтому отразил это в названии. Всё равно чутка подправил, может понравится...

2021-02-20 03:09 UTC, vatokato commented on src/components/reviews-list/reviews-list.jsx
> +Review.propTypes = {
не критично) просто они бесполезны :)

2021-02-20 03:09 UTC, merged