finished task 5-1
htmlacademy-react/1378865-six-cities-6 pull request #9
Opened 2021-02-21 22:00 UTC by nikitenkovit

не стал пока что добавлять редюсер для offers (добавлю, когда появится api). combineReducers с всего одним редюсером временно, потом буду добавлять остальные...

2021-02-22 13:22 UTC, vatokato requested changes
Вцелом все хорошо, молодец. Редакс и смена городов выглядят норм )

2021-02-22 13:22 UTC, vatokato commented on src/store/city/reducer.js
> +        city: action.payload
а зачем тебе в city еще один city? :)

можно просто
```
...action.payload
```

иначе теряется смысл в combine reducer

2021-02-22 13:22 UTC, vatokato commented on src/components/city-link/city-link.jsx
> +const CityLink = (props) => {
Очень странное решение: часть пропсов получать через коннектор, а часть через пропсы сверху.
Лучше выбрать один вариант получения, чтобы не потеряться )
В данном случае для комопнента, который рендерится в цикле я бы не подключал коннектор, а все пропсы получал сверху. Коннекторы как правило для более сложных компонентов

2021-02-22 13:22 UTC, vatokato commented on src/components/main-screen/main-screen.jsx
> +          {<Cities/>}
зачем фигурные скобки? :)

2021-02-22 13:22 UTC, vatokato commented on src/components/main-screen/main-screen.jsx
> +                {offers.length} places to stay in Amsterdam
лучше количество предварительно посчитать и передать пропсом

не критично

2021-02-22 15:43 UTC, nikitenkovit commented on src/index.js
> +import reducer from './store/root-reduser';
сделал)

2021-02-22 15:55 UTC, nikitenkovit commented on src/components/main-screen/main-screen.jsx
> +          {<Cities/>}
ппц) сделал...

2021-02-22 21:33 UTC, nikitenkovit commented on src/store/city/reducer.js
> +        city: action.payload
сделал

2021-02-22 21:36 UTC, nikitenkovit commented on src/components/city-link/city-link.jsx
> +const CityLink = (props) => {
сделал. оставил в конекторе только диспатч

2021-02-22 21:54 UTC, nikitenkovit commented on src/components/main-screen/main-screen.jsx
> +                {offers.length} places to stay in Amsterdam
сделаю в следующей домашке 5-2

2021-02-23 12:22 UTC, vatokato commented on src/components/city-link/city-link.jsx
> +const CityLink = (props) => {
я бы вообще коннетор убрал из такого компонента. но ладно, пусть будет, не критично.

2021-02-23 12:22 UTC, vatokato commented on src/components/main-screen/main-screen.jsx
> +                {offers.length} places to stay in Amsterdam
ок

2021-02-23 12:22 UTC, merged